# Generated by Django 5.0 on 2024-01-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('phone', models.CharField(max_length=32, verbose_name='手机号码')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('course', models.CharField(max_length=32, verbose_name='课程')),
                ('class_hours', models.IntegerField(blank=True, null=True, verbose_name='课时量')),
                ('duty_hours', models.FloatField(blank=True, null=True, verbose_name='值班折算节数')),
                ('extra_hours', models.FloatField(blank=True, null=True, verbose_name='额外工作折算节数')),
                ('total_hours', models.FloatField(blank=True, null=True, verbose_name='额总工作量节数')),
                ('work_score', models.FloatField(blank=True, null=True, verbose_name='额总工作量节数')),
                ('personal_score', models.FloatField(blank=True, null=True, verbose_name='教师个人成绩')),
                ('class_score', models.FloatField(blank=True, null=True, verbose_name='班级量化成绩')),
                ('group_score', models.FloatField(blank=True, null=True, verbose_name='教研组量化成绩')),
                ('total_score', models.FloatField(blank=True, null=True, verbose_name='总成绩')),
                ('note', models.CharField(blank=True, max_length=120, null=True, verbose_name='备注')),
                ('ranking', models.IntegerField(blank=True, null=True, verbose_name='名次')),
            ],
        ),
    ]
