# Generated by Django 5.0 on 2024-03-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chengji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zhunkaozheng', models.CharField(max_length=32, verbose_name='学生准考证号')),
                ('xingming', models.CharField(max_length=32, verbose_name='学生姓名')),
                ('banji', models.IntegerField(verbose_name='班级')),
                ('yuwen_score', models.IntegerField(verbose_name='语文成绩')),
                ('shuxue_score', models.IntegerField(verbose_name='数学成绩')),
                ('waiyu_score', models.IntegerField(verbose_name='外语成绩')),
                ('xuankao_1', models.CharField(max_length=32, verbose_name='选考科目1名称')),
                ('xuankao_1_score', models.IntegerField(verbose_name='选考1科目成绩')),
                ('xuankao_1_weici', models.IntegerField(verbose_name='选考1科目位次')),
                ('xuankao_2', models.CharField(max_length=32, verbose_name='选考科目2名称')),
                ('xuankao_2_score', models.IntegerField(verbose_name='选考2科目成绩')),
                ('xuankao_2_weici', models.IntegerField(verbose_name='选考2科目位次')),
                ('xuankao_3', models.CharField(max_length=32, verbose_name='选考科目3名称')),
                ('xuankao_3_score', models.IntegerField(verbose_name='选考3科目成绩')),
                ('xuankao_3_weici', models.IntegerField(verbose_name='选考3科目位次')),
                ('total_score', models.IntegerField(verbose_name='总分')),
                ('total_weici', models.IntegerField(verbose_name='总分位次')),
            ],
        ),
    ]
