# Generated by Django 5.0 on 2024-01-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_userinfo_creat_time_alter_userinfo_depart'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrettyNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('level', models.SmallIntegerField(choices=[(1, '等级1'), (2, '等级2'), (3, '等级3'), (4, '等级4')], default=1, verbose_name='等级')),
                ('status', models.SmallIntegerField(choices=[(1, '已售'), (2, '未售')], default=2, verbose_name='状态')),
            ],
        ),
    ]
