# Generated by Django 5.0 on 2024-11-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_alter_city_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=32, verbose_name='名称'),
        ),
    ]
